### ISSUE TITLE
$21 fix web extension pagination behaviour

### ISSUE THREAD

**Issue by yiwang** [localnative/localnative-bounty#1]
mirror of gitlab issue https://gitlab.com/yiwang/localnative/issues/2

Web extension is using a legacy pagination display (something like current page index/total page number)
desktop and mobile app implemented (start index - end index / total item count)
screenshot https://localnative.app/blog/2019/03/24/localnative-v0.3.8-release
Acceptance:
Implement / reuse same logic as in desktop app.

**Comment by ben-ying** [comment]
https://gitlab.com/localnative/localnative/-/commit/1f15707830a9fa63062227033cb71633549c222f

**Comment by ben-ying** [comment]
@yiwang please help to close this issue.
